<a href="https://colab.research.google.com/github/malavika2003/HouseCostPrediction/blob/main/HouseCostPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data= pd.read_csv('/content/Bengaluru_House_Data.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
data.shape

(13320, 9)

In [ ]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
for column in data.columns:
  print(data[column].value_counts())
  print("*"*20)

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64
********************
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: availability, Length: 81, dtype: int64
********************
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64
********************
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64
********************
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: society, Length: 2688, dtype: int64
********************
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: total_sqft, Length: 2117, dtype: int64
********************
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: bath, dtype: int64
********************
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64
********************
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: price, Length: 1994, dtype: int64
********************

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [ ]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
data['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [ ]:
data['location']=data['location'].fillna('Sarjapur  Road')

In [ ]:
data['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [ ]:
data['size'].isna().sum()

16

In [ ]:
data['size']=data['size'].fillna('2 BHK')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
data['bath']=data['bath'].fillna(data['bath'].median())

In [ ]:
data['bhk'] = data['size'].str.split().str.get(0).str.extract('(\d+)').astype(int)

In [ ]:
data[data.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [ ]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
def convertRange(x):
    if isinstance(x, float):
        return x

    temp = x.split()
    if len(temp) == 2:
        try:
            return (float(temp[0]) + float(temp[1])) / 2
        except:
            return None
    try:
        return float(x.replace('Sq.', '').strip())  # Remove 'Sq.' and any whitespace
    except:
        return None

In [ ]:
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [ ]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [ ]:
data['price_per_sqft']=data['price']*100000 / data['total_sqft']

In [ ]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [ ]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13073.000000  13320.000000  13320.000000  13320.000000    1.307300e+04
mean    1554.942029      2.688814    112.565627      2.802778    7.949600e+03
std     1238.458773      1.338754    148.971674      1.294496    1.072440e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.265734e+03
50%     1275.000000      2.000000     72.000000      3.000000    5.454545e+03
75%     1670.000000      3.000000    120.000000      3.000000    7.338057e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [ ]:
data['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [ ]:
data['location']=data['location'].apply(lambda x: x.strip())
location_count=data['location'].value_counts()

In [ ]:
location_count

Whitefield                        541
Sarjapur  Road                    400
Electronic City                   304
Kanakpura Road                    273
Thanisandra                       237
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1294, dtype: int64

In [ ]:
location_count_less_10=location_count[location_count<=10]
location_count_less_10

Dairy Circle                      10
Nagappa Reddy Layout              10
Basapura                          10
1st Block Koramangala             10
Sector 1 HSR Layout               10
                                  ..
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
singapura paradise                 1
Abshot Layout                      1
Name: location, Length: 1053, dtype: int64

In [ ]:
data['location']=data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [ ]:
data['location'].value_counts()

other                 2885
Whitefield             541
Sarjapur  Road         400
Electronic City        304
Kanakpura Road         273
                      ...
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: location, Length: 242, dtype: int64

In [ ]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13073.000000  13320.000000  13320.000000  13320.000000    1.307300e+04
mean    1554.942029      2.688814    112.565627      2.802778    7.949600e+03
std     1238.458773      1.338754    148.971674      1.294496    1.072440e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.265734e+03
50%     1275.000000      2.000000     72.000000      3.000000    5.454545e+03
75%     1670.000000      3.000000    120.000000      3.000000    7.338057e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [ ]:
(data['total_sqft']/data['bhk']).describe()

count    13073.000000
mean       573.254923
std        389.887823
min          0.250000
25%        472.000000
50%        551.000000
75%        625.000000
max      26136.000000
dtype: float64

In [ ]:
data=data[((data['total_sqft']/data['bhk'])>=300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12329.000000  12329.000000  12329.000000  12329.000000    12329.000000
mean    1590.166773      2.561441    111.444236      2.651472     6322.476758
std     1261.827604      1.072551    152.759322      0.973754     4187.479096
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1118.000000      2.000000     49.340000      2.000000     4207.119741
50%     1300.000000      2.000000     70.000000      3.000000     5300.000000
75%     1700.000000      3.000000    115.000000      3.000000     6938.483548
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [ ]:
data.shape

(12329, 7)

In [ ]:
data.price_per_sqft.describe()

count     12329.000000
mean       6322.476758
std        4187.479096
min         267.829813
25%        4207.119741
50%        5300.000000
75%        6938.483548
max      176470.588235
Name: price_per_sqft, dtype: float64

In [ ]:
def remove_outliers_sqft(df):
  df_output=pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m=np.mean(subdf.price_per_sqft)
    st=np.std(subdf.price_per_sqft)
    gen_df=subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <=(m+st))]
    df_output=pd.concat([df_output,gen_df],ignore_index=True)
  return df_output
data=remove_outliers_sqft(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10154.000000  10154.000000  10154.000000  10154.000000    10154.000000
mean    1502.755034      2.472129     91.120414      2.573666     5670.431136
std      873.959398      0.972214     86.251507      0.893601     2276.089730
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4242.424242
50%     1283.500000      2.000000     67.000000      2.000000     5184.504357
75%     1650.000000      3.000000    100.000000      3.000000     6451.612903
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [ ]:
def bhk_outlier_remover(df):
       exclude_indices=np.array([])
       for location, location_df in df.groupby('location'):
          bhk_stats ={}
          for bhk,bhk_df in location_df.groupby('bhk'):
              bhk_stats[bhk]={
                    'mean': np.mean(bhk_df.price_per_sqft),
                    'std': np.std(bhk_df.price_per_sqft),
                    'count':bhk_df.shape[0]
                     }
          for bhk,bhk_df in location_df.groupby('bhk'):
                stats = bhk_stats.get(bhk-1)
                if stats and stats['count']>5:
                        exclude_indices=np.append(exclude_indices,bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
       return df.drop(exclude_indices,axis='index')

In [ ]:
data=bhk_outlier_remover(data)

In [ ]:
data.shape

(7227, 7)

In [ ]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10145,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10146,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10149,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10150,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10153,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [ ]:
data.drop(columns=['size','price_per_sqft'],inplace=True)

In [ ]:
data

                  location  total_sqft  bath  price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10145                other      1200.0   2.0   70.0    2
10146                other      1800.0   1.0  200.0    1
10149                other      1353.0   2.0  110.0    2
10150                other       812.0   1.0   26.0    1
10153                other      3600.0   5.0  400.0    4

[7227 rows x 5 columns]

In [ ]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [ ]:
data.to_csv("Cleaned_data.csv")

In [ ]:
X=data.drop(columns=['price'])
y=data['price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(5781, 4)
(1446, 4)

In [ ]:
column_trans=make_column_transformer((OneHotEncoder(sparse=False),['location']),remainder='passthrough')

In [ ]:
scaler = StandardScaler()

In [ ]:
#xfrom sklearn.metrics.pairwise import normalize
#lr=LinearRegression(normalize=True)

In [ ]:
pipe=make_pipeline(column_trans,StandardScaler(with_mean=False),LinearRegression())

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler(with_mean=False)),
                ('linearregression', LinearRegression())])

In [ ]:
y_pred_lr=pipe.predict(X_test)

In [ ]:
r2_score(y_test,y_pred_lr)

0.8428161973901729

In [ ]:
lasso=Lasso()

In [ ]:
pipe=make_pipeline(column_trans,scaler,lasso)

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [ ]:
y_pred_lasso= pipe.predict(X_test)
r2_score(y_test,y_pred_lasso)

0.8422061212418402

In [ ]:
ridge=Ridge()

In [ ]:
pipe =make_pipeline(column_trans,scaler,ridge)

In [ ]:
pipe.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [ ]:
y_pred_ridge=pipe.predict(X_test)
r2_score(y_test,y_pred_ridge)

0.8433576092748734

In [ ]:
print("NO regularization: ",r2_score(y_test,y_pred_lr))
print("Lasso : ",r2_score(y_test,y_pred_lasso))
print("Ridge: ",r2_score(y_test,y_pred_ridge))

NO regularization:  0.8428161973901729
Lasso :  0.8422061212418402
Ridge:  0.8433576092748734

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))